### PR TITLE
Added 1 char checks

### PR DESCRIPTION
**Pull request by AdamJamesNaylor**

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
I think you have missed your chance to legitimately use some emojis like :goat: & :tent: on this one.

**Comment by AdamJamesNaylor** [comment]
Stevey B is testing some Slack integration with IFTTT so this was just a quick dummy PR.

PS there is no legitimate use of Emoji. Unless you are a twelve year old girl. :heart: :heart:

**Comment by AdamJamesNaylor** [comment]
Hence this upcoming cowboy-self-merge shenanigans!

**Comment by st3v3nhunt** [comment]
There must be a lot of 12 year olds in the UK to make it the fastest growing language ([source](http://www.bbc.co.uk/newsbeat/article/32793732/uks-fastest-growing-language-is-emoji)).

And you better tell Sony its audience for the [emoji film](http://www.bbc.co.uk/newsbeat/article/33635088/sony-pictures-buys-rights-to-make-an-emoji-movie) is going to be quite limited.

:girl:

**Comment by AdamJamesNaylor** [comment]
Did you just cite Newsbeat?
Never forget the time they referred to the then chancellor of the exchequer as the 'Tory top money man'.

World class journalism.

**Comment by st3v3nhunt** [comment]
It is my only source of 'news'.
They are doing it for the kids rather than the rich media moguls. They have fewer ulterior motives than most :wink:

**Comment by AdamJamesNaylor** [comment]
I can't help but feel this conversation is getting off topic.

Here's a news related emoji: :newspaper:

**Comment by st3v3nhunt** [comment]
:no_mouth: 
:bomb: 
:boom:

**Pull request merged**
